### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ampsarfraz** [michchan/expo-redux-saga-boilerplate#1]
hey Michchan,

Really like this boilerplate. Thanks for sharing this. It would be great if you can add some documentation to get started on using this.

Regards,
Sarfraz.

**Comment by michchan** [comment]
@ampsarfraz Thanks for appreciation and comment. Glad to hear someone like it. Agree, some description should be added for each folder usage. I will try to add them later, and will still add some changes according to what I am learning from other projects.
